spring.application.name=demo
# Para asegurar que Spring sirva los recursos estáticos
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
# Configuración para H2 en modo archivo
spring.datasource.url=jdbc:h2:file:./data/demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update